development:
  adapter: sqlite3
  database: db/asagao_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: asagao_test
  username: root
  password: nGh2i5och
  host: 192.168.33.12
  socket: /tmp/mysql.sock
  encoding: utf8

production:
  adapter: mysql2
  database: asagao_production
  username: root
  password: nGh2i5och
  host: 192.168.33.12
  socket: /tmp/mysql.sock
  encoding: utf8


